version: "3.8"
services:
    postgres:
        container_name: wepynaire_deploiement_postgres_29327_container
        image: postgres:latest
        working_dir: /app
        restart: always
        ports:
            - "29327:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - "postgres_wepynaire_deploiement_29327:/var/lib/postgresql"

volumes:
    postgres_wepynaire_deploiement_29327:
